# Generated by Django 4.2.7 on 2024-03-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryNameRus', models.CharField(max_length=255)),
                ('categoryNameEng', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialproduct')),
            ],
        ),
    ]
