# Generated by Django 4.2.7 on 2024-03-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_loandetaileddescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetailedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=1000)),
                ('loanDetail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bankloandetail')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.financialproduct')),
            ],
        ),
    ]
