# Generated by Django 4.2.7 on 2024-04-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_loandetaileddescription_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetaileddescription',
            name='bank_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandetaileddescription',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.financialproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandetaileddescription',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.productcategories'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoanDetailedDescription1',
        ),
    ]
